# Generated by Django 2.1.7 on 2019-03-30 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rso_manage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('place', models.CharField(max_length=64)),
                ('rso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rso_manage.RSO')),
            ],
        ),
        migrations.AddField(
            model_name='attending',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event'),
        ),
        migrations.AddField(
            model_name='attending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
