# Generated by Django 2.1.7 on 2019-04-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('rso_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rso_manage.RSO'),
        ),
        migrations.AddField(
            model_name='attending',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event'),
        ),
    ]
