# Generated by Django 2.1.7 on 2019-03-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_established', models.IntegerField()),
                ('college_association', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
    ]
